[package]
name = "expand"
version = "0.1.0"
edition = "2026"

[paths]
source = "src"
entry = "main.fab"

[paths.templates]
gnu = "../../common/gnu"

[build]
target = "rust"
kind = "bin"

[reader]
locale = "la"
