#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys
from typing import Any


DEFAULT_MODEL_DIR = pathlib.Path("/Users/ianzepp/ai/models/Qwen3-Embedding-0.6B")
DEFAULT_ORACLE_LABEL = "transformers-local-qwen3"
DEFAULT_VENV_PYTHON = pathlib.Path("/Users/ianzepp/ai/venvs/qwen3-embed-py313/bin/python")
DEFAULT_MAX_LENGTH = 512
TOLERANCE = 1e-6


def reexec_into_oracle_venv() -> None:
    if os.environ.get("FABER_QWEN3_ORACLE_REEXEC") == "1":
        return
    if not DEFAULT_VENV_PYTHON.exists():
        return
    if pathlib.Path(sys.prefix).resolve() == DEFAULT_VENV_PYTHON.parents[1].resolve():
        return
    os.environ["FABER_QWEN3_ORACLE_REEXEC"] = "1"
    os.execv(str(DEFAULT_VENV_PYTHON), [str(DEFAULT_VENV_PYTHON), *sys.argv])


def force_offline_huggingface() -> None:
    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
    os.environ.setdefault("HF_HOME", "/Users/ianzepp/ai/huggingface-cache")


def read_texts(path: pathlib.Path) -> list[str]:
    return [line.strip() for line in path.read_text().splitlines() if line.strip()]


def last_token_pool(last_hidden_states: Any, attention_mask: Any) -> Any:
    import torch

    left_padding = attention_mask[:, -1].sum() == attention_mask.shape[0]
    if left_padding:
        return last_hidden_states[:, -1]
    sequence_lengths = attention_mask.sum(dim=1) - 1
    batch_size = last_hidden_states.shape[0]
    return last_hidden_states[torch.arange(batch_size, device=last_hidden_states.device), sequence_lengths]


def embed(model_dir: pathlib.Path, texts: list[str], max_length: int) -> list[list[float]]:
    if not texts:
        raise ValueError("Qwen3 embedding oracle requires at least one input text")

    import torch
    import torch.nn.functional as F
    from transformers import AutoModel, AutoTokenizer

    torch.set_num_threads(min(8, os.cpu_count() or 1))
    tokenizer = AutoTokenizer.from_pretrained(
        model_dir,
        local_files_only=True,
        padding_side="left",
    )
    tokenizer.padding_side = "left"
    model = AutoModel.from_pretrained(
        model_dir,
        local_files_only=True,
        dtype=torch.float32,
    )
    model.eval()

    batch = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    with torch.no_grad():
        outputs = model(**batch)
        pooled = last_token_pool(outputs.last_hidden_state, batch["attention_mask"])
        vectors = F.normalize(pooled, p=2, dim=1)
    return [[float(value) for value in row] for row in vectors.tolist()]


def artifact(
    *,
    model_alias: str,
    source: str,
    oracle_label: str,
    texts: list[str],
    vectors: list[list[float]],
    max_length: int,
) -> dict[str, Any]:
    dimensions = len(vectors[0]) if vectors else 0
    return {
        "format": "fvi-stage2",
        "model": model_alias,
        "source": source,
        "status": "oracle-backed",
        "input_count": len(texts),
        "dimensions": dimensions,
        "normalization": "l2",
        "oracle": oracle_label,
        "batch": {
            "count": len(texts),
            "max_length": max_length,
            "pooling": "last-token",
            "device": "cpu",
        },
        "vectors": [
            {"id": index, "text": text, "values": values}
            for index, (text, values) in enumerate(zip(texts, vectors))
        ],
        "diagnostics": [
            "vectors generated by local Transformers Qwen3 oracle with local_files_only=True",
            "Faber-owned transformer execution not implemented",
        ],
    }


def max_abs_error(left: dict[str, Any], right: dict[str, Any]) -> float:
    left_vectors = left["vectors"]
    right_vectors = right["vectors"]
    if len(left_vectors) != len(right_vectors):
        raise ValueError("vector count mismatch")
    maximum = 0.0
    for index, (left_item, right_item) in enumerate(zip(left_vectors, right_vectors)):
        left_values = left_item["values"]
        right_values = right_item["values"]
        if len(left_values) != len(right_values):
            raise ValueError(f"dimension mismatch at vector {index}")
        for left_value, right_value in zip(left_values, right_values):
            maximum = max(maximum, abs(float(left_value) - float(right_value)))
    return maximum


def write_artifact(path: pathlib.Path, value: dict[str, Any]) -> None:
    path.write_text(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n")


def main() -> int:
    reexec_into_oracle_venv()
    force_offline_huggingface()

    parser = argparse.ArgumentParser(description="Generate a local Qwen3 Stage 4 oracle artifact")
    parser.add_argument("--model-dir", type=pathlib.Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--texts", type=pathlib.Path, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    parser.add_argument("--model-alias", default="mid/qwen3-embed-0.6b")
    parser.add_argument("--source", default="Qwen/Qwen3-Embedding-0.6B")
    parser.add_argument("--oracle-label", default=DEFAULT_ORACLE_LABEL)
    parser.add_argument("--max-length", type=int, default=DEFAULT_MAX_LENGTH)
    args = parser.parse_args()

    texts = read_texts(args.texts)
    vectors = embed(args.model_dir, texts, args.max_length)
    write_artifact(
        args.out,
        artifact(
            model_alias=args.model_alias,
            source=args.source,
            oracle_label=args.oracle_label,
            texts=texts,
            vectors=vectors,
            max_length=args.max_length,
        ),
    )
    print(f"wrote {len(texts)} vectors with dimension {len(vectors[0]) if vectors else 0} to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
