[functions."sqlite:sqlite.exsequi"]
symbol = "crate::shim::exsequi"

[functions."sqlite:sqlite.exsequi_batch"]
symbol = "crate::shim::exsequi_batch"

[functions."sqlite:sqlite.quaere"]
symbol = "crate::shim::quaere"

[functions."sqlite:sqlite.scalar"]
symbol = "crate::shim::scalar"

[functions."sqlite:sqlite.sha256_hex"]
symbol = "crate::shim::sha256_hex"

[shim]
path = "rust/shim.rs"
