#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json


def read_texts(path: str) -> list[str]:
    with open(path, "r", encoding="utf-8") as handle:
        return [line.strip() for line in handle.read().splitlines() if line.strip()]


def vector(index: int) -> list[float]:
    values = [0.0] * 1024
    values[index % 1024] = 1.0
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description="Hermetic fake Qwen3 oracle fixture")
    parser.add_argument("--texts", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--model-dir", required=True)
    parser.add_argument("--model-alias", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--oracle-label", required=True)
    args = parser.parse_args()

    texts = read_texts(args.texts)
    artifact = {
        "format": "fvi-stage2",
        "model": args.model_alias,
        "source": args.source,
        "status": "oracle-backed",
        "input_count": len(texts),
        "dimensions": 1024,
        "normalization": "l2",
        "oracle": args.oracle_label,
        "vectors": [
            {"id": index, "text": text, "values": vector(index)}
            for index, text in enumerate(texts)
        ],
        "diagnostics": [
            "vectors generated by hermetic fake Qwen3 oracle fixture"
        ],
    }
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(artifact, sort_keys=True, separators=(",", ":")) + "\n")
    print(f"wrote {len(texts)} vectors with dimension 1024 to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
